//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunRiseDbFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientInfo
    {
        public PatientInfo()
        {
            this.Contacts = new HashSet<Contact>();
            this.Handicaps = new HashSet<Handicap>();
            this.Illnesses = new HashSet<Illness>();
            this.PersonalContacts = new HashSet<PersonalContact>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> BloodTypeId { get; set; }
        public string Dislikes { get; set; }
        public string Comments { get; set; }
    
        public virtual BloodType BloodType { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Handicap> Handicaps { get; set; }
        public virtual ICollection<Illness> Illnesses { get; set; }
        public virtual ICollection<PersonalContact> PersonalContacts { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
