//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunRiseDbFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Caretakers = new HashSet<Caretaker>();
            this.PatientInfoes = new HashSet<PatientInfo>();
            this.Visits = new HashSet<Visit>();
        }
    
        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public int ContactNumber { get; set; }
        public int Role_id { get; set; }
        public string Gender { get; set; }
    
        public virtual ICollection<Caretaker> Caretakers { get; set; }
        public virtual ICollection<PatientInfo> PatientInfoes { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
